services:
  db:
    image: postgres:${PG_VERSION:-18.6-alpine}
    container_name: juice-journal-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: juice_journal_db
      POSTGRES_USER: juice_journal_usr
      POSTGRES_PASSWORD: juice_journal_pwd
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  migrator:
    image: ghcr.io/amacneil/dbmate:${DBMATE_VERSION:-2.35.1}
    container_name: juice-journal-migrator
    restart: no
    environment:
      DATABASE_URL: postgres://juice_journal_usr:juice_journal_pwd@db:5432/juice_journal_db?sslmode=disable
      DBMATE_NO_DUMP_SCHEMA: true
    volumes:
      - ./db:/db
    command: up
    depends_on:
      db:
        condition: service_healthy

  weather:
    image: dhi.io/wiremock:${WIREMOCK_VERSION:-3.13}
    ports:
      - "8081:8080"
    volumes:
      - ./data/mocks:/home/wiremock/mappings
      - ./data/forecast.mock.json:/home/wiremock/__files/forecast.json
      - ./data/archive.mock.json:/home/wiremock/__files/archive.json

volumes:
  pg_data:
    driver: local
