POST {{$dotenv PROTOCOL}}://{{$dotenv HOST}}:{{$dotenv PORT}}/api/trips
Content-Type: application/json

{
	"vehicle_id": "550e8400-e29b-41d4-a716-446655440002",
	"start_time": "2026-07-12T06:45:41Z",
	"end_time": "2026-07-12T06:45:43Z",
	"daypart": "morning",
	"duration_min": 1,
	"distance_km": 1
}
